//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""gameplay"",
            ""id"": ""1f3f14b1-df35-41f4-bf3e-ed17d9dbb230"",
            ""actions"": [
                {
                    ""name"": ""PointerPos"",
                    ""type"": ""PassThrough"",
                    ""id"": ""689402f5-a67b-403c-a311-44e3f1a4c3a9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PointerScroll"",
                    ""type"": ""Value"",
                    ""id"": ""838e0c49-b4a9-48c3-a7a8-d09aae80b6f3"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraPan"",
                    ""type"": ""Value"",
                    ""id"": ""7cfa4fb0-c5a7-455e-91b9-97bb3cc2a027"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DrawEntitySelectionBox"",
                    ""type"": ""Value"",
                    ""id"": ""7e3b53f7-f42b-4cf9-987b-3df3fd109ef3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ToggleSelectiveSelection"",
                    ""type"": ""Button"",
                    ""id"": ""f8bb6816-2fc5-460d-ae74-71a7f28ede05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerClickSelectEntity"",
                    ""type"": ""Button"",
                    ""id"": ""084eaf3a-c7b0-4856-bb28-9c88b4d27e3e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerClickGiveCommand"",
                    ""type"": ""Button"",
                    ""id"": ""96a8f451-4a50-4662-8f3c-c673119ba214"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraDrag"",
                    ""type"": ""Button"",
                    ""id"": ""38257d3a-856d-49e1-a626-efa3df2fb8fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a17cd52d-ed6d-4ba4-8485-85f645d4d93b"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""PointerPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da746b23-1320-4024-8fef-8e66616b2092"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""PointerScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Middle click & drag"",
                    ""id"": ""d57dd7dd-2c74-40d7-9664-c4ac0349511e"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraPan"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""8e842856-9056-40a1-ba8b-81e9ef4facaa"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraPan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Binding"",
                    ""id"": ""06d29885-3778-4fe8-9547-93170d82f4a3"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraPan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WSAD 2D Vector"",
                    ""id"": ""94eb0c7a-e1e9-4569-908c-00d4196e65c1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraPan"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""77ec1da9-8dba-4650-b3af-2f106e148010"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraPan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bf657ade-c1b5-401f-833e-99c8d383a69d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraPan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ea0eab85-7a1a-4d5a-8d90-866c2fd3ca85"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraPan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""97632ce1-3310-4cc3-8782-2d778b7a1983"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraPan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LMB Click&Drag"",
                    ""id"": ""33933ea5-0a9f-4ed6-a434-8992f0c2158f"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DrawEntitySelectionBox"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e3c6b94c-b2ab-4ab0-a0d3-8253b27228e1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""DrawEntitySelectionBox"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0caf206d-ad85-4e84-9e2a-b06a5cc46ff9"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""DrawEntitySelectionBox"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0c8fa557-dc43-4a01-8cb4-39ed60e665eb"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ToggleSelectiveSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f3fc543-a3aa-4a61-b38b-d5a921c287fd"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee0dcde5-a811-4189-a873-2d8fb1174ca4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""TriggerClickSelectEntity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17afa8aa-c64f-4d5e-9dfd-1525adefff7a"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""TriggerClickGiveCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // gameplay
        m_gameplay = asset.FindActionMap("gameplay", throwIfNotFound: true);
        m_gameplay_PointerPos = m_gameplay.FindAction("PointerPos", throwIfNotFound: true);
        m_gameplay_PointerScroll = m_gameplay.FindAction("PointerScroll", throwIfNotFound: true);
        m_gameplay_CameraPan = m_gameplay.FindAction("CameraPan", throwIfNotFound: true);
        m_gameplay_DrawEntitySelectionBox = m_gameplay.FindAction("DrawEntitySelectionBox", throwIfNotFound: true);
        m_gameplay_ToggleSelectiveSelection = m_gameplay.FindAction("ToggleSelectiveSelection", throwIfNotFound: true);
        m_gameplay_TriggerClickSelectEntity = m_gameplay.FindAction("TriggerClickSelectEntity", throwIfNotFound: true);
        m_gameplay_TriggerClickGiveCommand = m_gameplay.FindAction("TriggerClickGiveCommand", throwIfNotFound: true);
        m_gameplay_CameraDrag = m_gameplay.FindAction("CameraDrag", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // gameplay
    private readonly InputActionMap m_gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_gameplay_PointerPos;
    private readonly InputAction m_gameplay_PointerScroll;
    private readonly InputAction m_gameplay_CameraPan;
    private readonly InputAction m_gameplay_DrawEntitySelectionBox;
    private readonly InputAction m_gameplay_ToggleSelectiveSelection;
    private readonly InputAction m_gameplay_TriggerClickSelectEntity;
    private readonly InputAction m_gameplay_TriggerClickGiveCommand;
    private readonly InputAction m_gameplay_CameraDrag;
    public struct GameplayActions
    {
        private @PlayerInputActions m_Wrapper;
        public GameplayActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PointerPos => m_Wrapper.m_gameplay_PointerPos;
        public InputAction @PointerScroll => m_Wrapper.m_gameplay_PointerScroll;
        public InputAction @CameraPan => m_Wrapper.m_gameplay_CameraPan;
        public InputAction @DrawEntitySelectionBox => m_Wrapper.m_gameplay_DrawEntitySelectionBox;
        public InputAction @ToggleSelectiveSelection => m_Wrapper.m_gameplay_ToggleSelectiveSelection;
        public InputAction @TriggerClickSelectEntity => m_Wrapper.m_gameplay_TriggerClickSelectEntity;
        public InputAction @TriggerClickGiveCommand => m_Wrapper.m_gameplay_TriggerClickGiveCommand;
        public InputAction @CameraDrag => m_Wrapper.m_gameplay_CameraDrag;
        public InputActionMap Get() { return m_Wrapper.m_gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @PointerPos.started += instance.OnPointerPos;
            @PointerPos.performed += instance.OnPointerPos;
            @PointerPos.canceled += instance.OnPointerPos;
            @PointerScroll.started += instance.OnPointerScroll;
            @PointerScroll.performed += instance.OnPointerScroll;
            @PointerScroll.canceled += instance.OnPointerScroll;
            @CameraPan.started += instance.OnCameraPan;
            @CameraPan.performed += instance.OnCameraPan;
            @CameraPan.canceled += instance.OnCameraPan;
            @DrawEntitySelectionBox.started += instance.OnDrawEntitySelectionBox;
            @DrawEntitySelectionBox.performed += instance.OnDrawEntitySelectionBox;
            @DrawEntitySelectionBox.canceled += instance.OnDrawEntitySelectionBox;
            @ToggleSelectiveSelection.started += instance.OnToggleSelectiveSelection;
            @ToggleSelectiveSelection.performed += instance.OnToggleSelectiveSelection;
            @ToggleSelectiveSelection.canceled += instance.OnToggleSelectiveSelection;
            @TriggerClickSelectEntity.started += instance.OnTriggerClickSelectEntity;
            @TriggerClickSelectEntity.performed += instance.OnTriggerClickSelectEntity;
            @TriggerClickSelectEntity.canceled += instance.OnTriggerClickSelectEntity;
            @TriggerClickGiveCommand.started += instance.OnTriggerClickGiveCommand;
            @TriggerClickGiveCommand.performed += instance.OnTriggerClickGiveCommand;
            @TriggerClickGiveCommand.canceled += instance.OnTriggerClickGiveCommand;
            @CameraDrag.started += instance.OnCameraDrag;
            @CameraDrag.performed += instance.OnCameraDrag;
            @CameraDrag.canceled += instance.OnCameraDrag;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @PointerPos.started -= instance.OnPointerPos;
            @PointerPos.performed -= instance.OnPointerPos;
            @PointerPos.canceled -= instance.OnPointerPos;
            @PointerScroll.started -= instance.OnPointerScroll;
            @PointerScroll.performed -= instance.OnPointerScroll;
            @PointerScroll.canceled -= instance.OnPointerScroll;
            @CameraPan.started -= instance.OnCameraPan;
            @CameraPan.performed -= instance.OnCameraPan;
            @CameraPan.canceled -= instance.OnCameraPan;
            @DrawEntitySelectionBox.started -= instance.OnDrawEntitySelectionBox;
            @DrawEntitySelectionBox.performed -= instance.OnDrawEntitySelectionBox;
            @DrawEntitySelectionBox.canceled -= instance.OnDrawEntitySelectionBox;
            @ToggleSelectiveSelection.started -= instance.OnToggleSelectiveSelection;
            @ToggleSelectiveSelection.performed -= instance.OnToggleSelectiveSelection;
            @ToggleSelectiveSelection.canceled -= instance.OnToggleSelectiveSelection;
            @TriggerClickSelectEntity.started -= instance.OnTriggerClickSelectEntity;
            @TriggerClickSelectEntity.performed -= instance.OnTriggerClickSelectEntity;
            @TriggerClickSelectEntity.canceled -= instance.OnTriggerClickSelectEntity;
            @TriggerClickGiveCommand.started -= instance.OnTriggerClickGiveCommand;
            @TriggerClickGiveCommand.performed -= instance.OnTriggerClickGiveCommand;
            @TriggerClickGiveCommand.canceled -= instance.OnTriggerClickGiveCommand;
            @CameraDrag.started -= instance.OnCameraDrag;
            @CameraDrag.performed -= instance.OnCameraDrag;
            @CameraDrag.canceled -= instance.OnCameraDrag;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @gameplay => new GameplayActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IGameplayActions
    {
        void OnPointerPos(InputAction.CallbackContext context);
        void OnPointerScroll(InputAction.CallbackContext context);
        void OnCameraPan(InputAction.CallbackContext context);
        void OnDrawEntitySelectionBox(InputAction.CallbackContext context);
        void OnToggleSelectiveSelection(InputAction.CallbackContext context);
        void OnTriggerClickSelectEntity(InputAction.CallbackContext context);
        void OnTriggerClickGiveCommand(InputAction.CallbackContext context);
        void OnCameraDrag(InputAction.CallbackContext context);
    }
}
