//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""gameplay"",
            ""id"": ""1f3f14b1-df35-41f4-bf3e-ed17d9dbb230"",
            ""actions"": [
                {
                    ""name"": ""PointerPos"",
                    ""type"": ""PassThrough"",
                    ""id"": ""689402f5-a67b-403c-a311-44e3f1a4c3a9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PointerScroll"",
                    ""type"": ""Value"",
                    ""id"": ""838e0c49-b4a9-48c3-a7a8-d09aae80b6f3"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PointerClick"",
                    ""type"": ""Value"",
                    ""id"": ""cb4a5c07-9b20-4c71-b119-0a7f5cf06d69"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PointerClickDrag"",
                    ""type"": ""Button"",
                    ""id"": ""45ab8b90-5d69-48c0-b0b0-57f088b134d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""47c26cba-6620-42d1-88ad-7631082cba96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraMove"",
                    ""type"": ""Value"",
                    ""id"": ""7cfa4fb0-c5a7-455e-91b9-97bb3cc2a027"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DrawSelectionBox"",
                    ""type"": ""Value"",
                    ""id"": ""7e3b53f7-f42b-4cf9-987b-3df3fd109ef3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SpecialSelection"",
                    ""type"": ""Button"",
                    ""id"": ""f8bb6816-2fc5-460d-ae74-71a7f28ede05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a17cd52d-ed6d-4ba4-8485-85f645d4d93b"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""PointerPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da746b23-1320-4024-8fef-8e66616b2092"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""PointerScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef05ad36-0017-4894-9068-ae2e00e57e2d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""PointerClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed76596c-9f41-45aa-b065-7d011a0d6e44"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""PointerClickDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0895c712-eeb9-4111-8e5e-fc8ed9158b5d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Middle click & drag"",
                    ""id"": ""d57dd7dd-2c74-40d7-9664-c4ac0349511e"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2,ScaleVector2(x=0.035,y=0.035)"",
                    ""groups"": """",
                    ""action"": ""CameraMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""8e842856-9056-40a1-ba8b-81e9ef4facaa"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Binding"",
                    ""id"": ""06d29885-3778-4fe8-9547-93170d82f4a3"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WSAD 2D Vector"",
                    ""id"": ""94eb0c7a-e1e9-4569-908c-00d4196e65c1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""77ec1da9-8dba-4650-b3af-2f106e148010"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bf657ade-c1b5-401f-833e-99c8d383a69d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ea0eab85-7a1a-4d5a-8d90-866c2fd3ca85"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""97632ce1-3310-4cc3-8782-2d778b7a1983"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""33933ea5-0a9f-4ed6-a434-8992f0c2158f"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DrawSelectionBox"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e3c6b94c-b2ab-4ab0-a0d3-8253b27228e1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""DrawSelectionBox"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0caf206d-ad85-4e84-9e2a-b06a5cc46ff9"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""DrawSelectionBox"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0c8fa557-dc43-4a01-8cb4-39ed60e665eb"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""SpecialSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // gameplay
        m_gameplay = asset.FindActionMap("gameplay", throwIfNotFound: true);
        m_gameplay_PointerPos = m_gameplay.FindAction("PointerPos", throwIfNotFound: true);
        m_gameplay_PointerScroll = m_gameplay.FindAction("PointerScroll", throwIfNotFound: true);
        m_gameplay_PointerClick = m_gameplay.FindAction("PointerClick", throwIfNotFound: true);
        m_gameplay_PointerClickDrag = m_gameplay.FindAction("PointerClickDrag", throwIfNotFound: true);
        m_gameplay_Newaction = m_gameplay.FindAction("New action", throwIfNotFound: true);
        m_gameplay_CameraMove = m_gameplay.FindAction("CameraMove", throwIfNotFound: true);
        m_gameplay_DrawSelectionBox = m_gameplay.FindAction("DrawSelectionBox", throwIfNotFound: true);
        m_gameplay_SpecialSelection = m_gameplay.FindAction("SpecialSelection", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // gameplay
    private readonly InputActionMap m_gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_gameplay_PointerPos;
    private readonly InputAction m_gameplay_PointerScroll;
    private readonly InputAction m_gameplay_PointerClick;
    private readonly InputAction m_gameplay_PointerClickDrag;
    private readonly InputAction m_gameplay_Newaction;
    private readonly InputAction m_gameplay_CameraMove;
    private readonly InputAction m_gameplay_DrawSelectionBox;
    private readonly InputAction m_gameplay_SpecialSelection;
    public struct GameplayActions
    {
        private @PlayerInputActions m_Wrapper;
        public GameplayActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PointerPos => m_Wrapper.m_gameplay_PointerPos;
        public InputAction @PointerScroll => m_Wrapper.m_gameplay_PointerScroll;
        public InputAction @PointerClick => m_Wrapper.m_gameplay_PointerClick;
        public InputAction @PointerClickDrag => m_Wrapper.m_gameplay_PointerClickDrag;
        public InputAction @Newaction => m_Wrapper.m_gameplay_Newaction;
        public InputAction @CameraMove => m_Wrapper.m_gameplay_CameraMove;
        public InputAction @DrawSelectionBox => m_Wrapper.m_gameplay_DrawSelectionBox;
        public InputAction @SpecialSelection => m_Wrapper.m_gameplay_SpecialSelection;
        public InputActionMap Get() { return m_Wrapper.m_gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @PointerPos.started += instance.OnPointerPos;
            @PointerPos.performed += instance.OnPointerPos;
            @PointerPos.canceled += instance.OnPointerPos;
            @PointerScroll.started += instance.OnPointerScroll;
            @PointerScroll.performed += instance.OnPointerScroll;
            @PointerScroll.canceled += instance.OnPointerScroll;
            @PointerClick.started += instance.OnPointerClick;
            @PointerClick.performed += instance.OnPointerClick;
            @PointerClick.canceled += instance.OnPointerClick;
            @PointerClickDrag.started += instance.OnPointerClickDrag;
            @PointerClickDrag.performed += instance.OnPointerClickDrag;
            @PointerClickDrag.canceled += instance.OnPointerClickDrag;
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
            @CameraMove.started += instance.OnCameraMove;
            @CameraMove.performed += instance.OnCameraMove;
            @CameraMove.canceled += instance.OnCameraMove;
            @DrawSelectionBox.started += instance.OnDrawSelectionBox;
            @DrawSelectionBox.performed += instance.OnDrawSelectionBox;
            @DrawSelectionBox.canceled += instance.OnDrawSelectionBox;
            @SpecialSelection.started += instance.OnSpecialSelection;
            @SpecialSelection.performed += instance.OnSpecialSelection;
            @SpecialSelection.canceled += instance.OnSpecialSelection;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @PointerPos.started -= instance.OnPointerPos;
            @PointerPos.performed -= instance.OnPointerPos;
            @PointerPos.canceled -= instance.OnPointerPos;
            @PointerScroll.started -= instance.OnPointerScroll;
            @PointerScroll.performed -= instance.OnPointerScroll;
            @PointerScroll.canceled -= instance.OnPointerScroll;
            @PointerClick.started -= instance.OnPointerClick;
            @PointerClick.performed -= instance.OnPointerClick;
            @PointerClick.canceled -= instance.OnPointerClick;
            @PointerClickDrag.started -= instance.OnPointerClickDrag;
            @PointerClickDrag.performed -= instance.OnPointerClickDrag;
            @PointerClickDrag.canceled -= instance.OnPointerClickDrag;
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
            @CameraMove.started -= instance.OnCameraMove;
            @CameraMove.performed -= instance.OnCameraMove;
            @CameraMove.canceled -= instance.OnCameraMove;
            @DrawSelectionBox.started -= instance.OnDrawSelectionBox;
            @DrawSelectionBox.performed -= instance.OnDrawSelectionBox;
            @DrawSelectionBox.canceled -= instance.OnDrawSelectionBox;
            @SpecialSelection.started -= instance.OnSpecialSelection;
            @SpecialSelection.performed -= instance.OnSpecialSelection;
            @SpecialSelection.canceled -= instance.OnSpecialSelection;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @gameplay => new GameplayActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IGameplayActions
    {
        void OnPointerPos(InputAction.CallbackContext context);
        void OnPointerScroll(InputAction.CallbackContext context);
        void OnPointerClick(InputAction.CallbackContext context);
        void OnPointerClickDrag(InputAction.CallbackContext context);
        void OnNewaction(InputAction.CallbackContext context);
        void OnCameraMove(InputAction.CallbackContext context);
        void OnDrawSelectionBox(InputAction.CallbackContext context);
        void OnSpecialSelection(InputAction.CallbackContext context);
    }
}
